[build-system]
requires = ["setuptools>=61.0", "discordpy~=2.0", "toml~=0.10"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["blimp"]

[project]
name = "blimp"
version = "2.5.0"
authors = [
  { name="Cass Dingenskirchen", email="admin@dingenskirchen.org" },
]
description = "A small example package"
requires-python = ">=3.10"

[project.scripts]
blimp = "blimp:__main__"
