[tool.poetry]
name = "blimp"
version = "1.0.1"
description = "The BLIMP Levitating Intercommunication Management Programme, a Discord bot."
authors = ["Cassidy Dingenskirchen <admin@15318.de>"]
license = "AGPL-3.0"

[tool.poetry.dependencies]
python = "^3.7"
"discord.py" = "~1.5"
toml = "^0.10.1"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
pylint = "^2.6.0"

[tool.poetry.scripts]
blimp = "blimp.__main__:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
