from discord.ext import commands

from ..customizations import Blimp, Unauthorized
from .alias import MaybeAliasedTextChannel


class Logging(Blimp.Cog):
    "Watching with ten thousand eyes."

    @commands.group()
    async def logging(self, ctx: Blimp.Context):
        """Set up logging for your server to keep you informed on BLIMP's actions.

        Currently, logs are generated by **configuration changes** for logging, Boards, Kiosks,
        Slowmodes, Tickets, Triggers, and the Welcome and Goodbye logs. Additional logs are
        generated for individual **ticket creation and deletion**, as well as ticket **add/remove
        events**. **Channel bans** and unbans also are logged, as are changes to **channel
        names/topics** made through BLIMP."""

    @commands.command(parent=logging, name="set")
    async def _set(self, ctx: Blimp.Context, channel: MaybeAliasedTextChannel):
        "Set the logging channel."
        if not ctx.privileged_modify(channel.guild):
            raise Unauthorized()

        await ctx.bot.post_log(
            channel.guild,
            f"{ctx.author} updated logging channel to {channel.mention}.",
            color=ctx.Color.I_GUESS,
        )

        ctx.database.execute(
            """INSERT OR REPLACE INTO logging_configuration(guild_oid, channel_oid)
            VALUES(:guild_oid, :channel_oid)""",
            {
                "channel_oid": ctx.objects.make_object(tc=channel.id),
                "guild_oid": ctx.objects.make_object(g=channel.guild.id),
            },
        )

        await ctx.reply(f"*New logs will be posted in {channel.mention}.*")
